version: '3.3'

services:
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=surveysbase

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
    - 8080:8080
    environment:
      - SPRING_DATASOURCE_JDBC-URL=jdbc:postgresql://db:5432/surveysbase
    depends_on:
      - db

volumes:
  pgdata: