spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/surveysbase
    username: postgres
    password: postgrespass
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: create-drop
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    show-sql: true

logging:
  level:
    org.springframework: INFO