version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=surveysbase

  app:
    image: survey:latest
    build: .
    ports:
    - 8080:8080
    environment:
      - SPRING_DATASOURCE_JDBC-URL=jdbc:postgresql://db:5432/surveysbase
    depends_on:
      - db

volumes:
  pgdata: